-- MySQL Script generated by MySQL Workbench
-- Tue Oct  6 02:24:21 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema butterfly_pixbit_v2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema butterfly_pixbit_v2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `butterfly_pixbit_v2` DEFAULT CHARACTER SET utf8 ;
USE `butterfly_pixbit_v2` ;

-- -----------------------------------------------------
-- Table `butterfly_pixbit_v2`.`genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `butterfly_pixbit_v2`.`genre` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `gname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `butterfly_pixbit_v2`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `butterfly_pixbit_v2`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `nameU` VARCHAR(50) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `image` VARCHAR(100) NOT NULL,
  `admin` TINYINT(4) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `butterfly_pixbit_v2`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `butterfly_pixbit_v2`.`products` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `genre` INT(11) NOT NULL,
  `requisito` VARCHAR(500) NOT NULL,
  `descripcion` VARCHAR(800) NOT NULL,
  `propiedad` TINYINT(4) NOT NULL,
  `price` INT(11) NOT NULL,
  `image` VARCHAR(100) NOT NULL,
  `id_genre` INT(11) NOT NULL,
  `id_users` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_genre_idx` (`id_genre` ASC),
  INDEX `id_users_idx` (`id_users` ASC),
  CONSTRAINT `id_genre`
    FOREIGN KEY (`id_genre`)
    REFERENCES `butterfly_pixbit_v2`.`genre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_users`
    FOREIGN KEY (`id_users`)
    REFERENCES `butterfly_pixbit_v2`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `butterfly_pixbit_v2`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `butterfly_pixbit_v2`.`carrito` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `cantidad` INT(11) NOT NULL,
  `id_product` INT(11) NOT NULL,
  `id_user` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_product_idx` (`id_product` ASC),
  INDEX `id_user_idx` (`id_user` ASC),
  CONSTRAINT `id_product`
    FOREIGN KEY (`id_product`)
    REFERENCES `butterfly_pixbit_v2`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_user`
    FOREIGN KEY (`id_user`)
    REFERENCES `butterfly_pixbit_v2`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
